server:
  port: 8761

spring:
  application:
    name: registry
  security:
    user:
      name: limbo
      password: 123456



eureka:
  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/






